import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import notoSansUrl from
  "../assets/fonts/NotoSans-Regular.ttf?url";

function formatCurrency(value) {
  return `₹${Number(value).toLocaleString("en-IN", {
    minimumFractionDigits: 0,
    maximumFractionDigits: 2,
  })}`;
}

function formatCategory(category) {
  return String(category || "OTHER")
    .toLowerCase()
    .replace(/_/g, " ")
    .replace(/\b\w/g, (letter) =>
      letter.toUpperCase()
    );
}

function formatDate(dateValue) {
  if (!dateValue) {
    return "";
  }

  const [year, month, day] = dateValue.split("-");

  return new Date(
    Number(year),
    Number(month) - 1,
    Number(day)
  ).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
}

function arrayBufferToBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;

  let binary = "";

  for (
    let index = 0;
    index < bytes.length;
    index += chunkSize
  ) {
    const chunk = bytes.subarray(
      index,
      Math.min(index + chunkSize, bytes.length)
    );

    binary += String.fromCharCode(...chunk);
  }

  return window.btoa(binary);
}

async function loadUnicodeFont(document) {
  const response = await fetch(notoSansUrl);

  if (!response.ok) {
    throw new Error(
      `Unable to load PDF font: ${response.status}`
    );
  }

  const fontBuffer = await response.arrayBuffer();
  const fontBase64 =
    arrayBufferToBase64(fontBuffer);

  document.addFileToVFS(
    "NotoSans-Regular.ttf",
    fontBase64
  );

  document.addFont(
    "NotoSans-Regular.ttf",
    "NotoSans",
    "normal"
  );

  document.setFont("NotoSans", "normal");
}

export async function exportExpensesToPdf(
  expenses = [],
  analytics = {}
) {
  const document = new jsPDF();

  await loadUnicodeFont(document);

  const {
    totalSpent = 0,
    averageExpense = 0,
    transactionCount = expenses.length,
  } = analytics;

  document.setFont("NotoSans", "normal");
  document.setTextColor(17, 24, 39);

  document.setFontSize(22);
  document.text("ExpenseAI", 14, 18);

  document.setFontSize(14);
  document.text("Expense Report", 14, 28);

  document.setFontSize(10);
  document.setTextColor(100, 116, 139);

  document.text(
    `Generated: ${new Date().toLocaleDateString(
      "en-IN",
      {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }
    )}`,
    14,
    36
  );

  document.setTextColor(17, 24, 39);
  document.setFontSize(11);

  document.text(
    `Total spent: ${formatCurrency(totalSpent)}`,
    14,
    48
  );

  document.text(
    `Transactions: ${transactionCount}`,
    14,
    56
  );

  document.text(
    `Average expense: ${formatCurrency(
      averageExpense
    )}`,
    14,
    64
  );

  const rows = expenses.map((expense) => [
    expense.item || "",
    formatCategory(expense.category),
    formatCurrency(expense.amount),
    formatDate(expense.date),
  ]);

  autoTable(document, {
    startY: 74,

    head: [
      ["Item", "Category", "Amount", "Date"],
    ],

    body: rows,

    styles: {
      font: "NotoSans",
      fontStyle: "normal",
      fontSize: 9,
      cellPadding: 3,
      textColor: [55, 65, 81],
    },

    headStyles: {
      font: "NotoSans",
      fontStyle: "normal",
      fillColor: [37, 99, 235],
      textColor: [255, 255, 255],
    },

    alternateRowStyles: {
      fillColor: [248, 250, 252],
    },

    columnStyles: {
      2: {
        halign: "right",
      },
    },

    didDrawPage: () => {
      const pageHeight =
        document.internal.pageSize.getHeight();

      document.setFont("NotoSans", "normal");
      document.setFontSize(8);
      document.setTextColor(100, 116, 139);

      document.text(
        "Generated by ExpenseAI",
        14,
        pageHeight - 10
      );
    },
  });

  const dateSuffix = new Date()
    .toISOString()
    .slice(0, 10);

  document.save(
    `expense-report-${dateSuffix}.pdf`
  );
}